# Generated by Django 3.1.3 on 2020-11-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorss', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='introimagesmodel',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='introimagesmodel',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
