# Generated by Django 3.1.3 on 2020-11-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorss', '0004_projectsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='body_post',
            field=models.TextField(blank=True, verbose_name='Текст на картинке'),
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='title_image',
            field=models.CharField(blank=True, max_length=250, verbose_name='Заголовок картинок'),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='body',
            field=models.TextField(verbose_name='Текст статьи'),
        ),
    ]
