# Generated by Django 3.1.3 on 2020-11-16 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dorss', '0007_auto_20201116_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('body', models.TextField(verbose_name='Текст статьи')),
                ('image', models.ImageField(upload_to='project/%Y/')),
                ('title_image', models.CharField(blank=True, max_length=250, verbose_name='Заголовок картинок')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.AddField(
            model_name='imageproductionmodel',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
