# Generated by Django 3.1.3 on 2020-11-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorss', '0008_auto_20201116_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproductionmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='production/%Y/'),
        ),
    ]
