# Generated by Django 3.1.3 on 2020-11-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorss', '0009_auto_20201116_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproductionmodel',
            name='image',
        ),
    ]
