# Generated by Django 3.1.3 on 2020-11-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorss', '0010_remove_imageproductionmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproductionmodel',
            name='body',
        ),
        migrations.AddField(
            model_name='imageproductionmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='production/%Y/'),
        ),
    ]
