# Generated by Django 3.1.3 on 2020-11-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorss', '0011_auto_20201116_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='body',
            field=models.TextField(verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(upload_to='news/%Y/'),
        ),
    ]
