# Generated by Django 3.1.3 on 2020-11-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorss', '0015_remove_servicemodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageServiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='service/%Y/')),
            ],
            options={
                'verbose_name_plural': 'Slide сервис',
            },
        ),
    ]
