# Generated by Django 3.1.3 on 2020-11-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorss', '0017_remove_servicemodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
