# Generated by Django 3.1.3 on 2020-11-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorss', '0019_feedbackmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormServiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('service_name', models.CharField(max_length=250)),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Заказать услугу',
            },
        ),
        migrations.AlterModelOptions(
            name='imageproductionmodel',
            options={'verbose_name_plural': 'Слайдер Production'},
        ),
        migrations.AlterModelOptions(
            name='imageservicemodel',
            options={'verbose_name_plural': 'Изображения service'},
        ),
        migrations.AlterModelOptions(
            name='productionmodels',
            options={'verbose_name_plural': 'Раздел Production'},
        ),
    ]
