# Generated by Django 3.1.3 on 2020-11-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorss', '0020_auto_20201118_1730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormServiceModel',
            new_name='ServiceFormModel',
        ),
    ]
