# Generated by Django 3.1.3 on 2020-11-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorss', '0021_auto_20201118_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('organization', models.CharField(max_length=200, verbose_name='Организация')),
                ('organization_object', models.CharField(max_length=200, verbose_name='Объект')),
                ('variety', models.CharField(max_length=200, verbose_name='Вид покрытия')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Количество')),
                ('supply', models.DateField(max_length=200, verbose_name='Срок поставки')),
                ('comment', models.TextField(verbose_name='Коментарий')),
            ],
        ),
    ]
