# Generated by Django 3.1.3 on 2020-11-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorss', '0022_applicationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество'),
        ),
    ]
