# Generated by Django 3.1.3 on 2020-11-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorss', '0025_auto_20201119_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageservicemodel',
            name='image_serv',
            field=models.FileField(upload_to='service/%Y/'),
        ),
    ]
